### ISSUE TITLE
CMIS EI Connector

### ISSUE THREAD

**Issue by kesavany** [wso2/extensions-roadmap#11]
**Description:**
Content Management Interoperability Services (CMIS) is an open standard that allows different content management systems to inter-operate over the Internet. Currently, we do not have the EI connector for CMIS.

**Suggested Labels:**
New Feature, EI- 6.1.1, CMIS

**Suggested Assignees:**
N/A

**Affected Product Version:**
N/A

**OS, DB, other environment details and versions:**    
N/A

**Steps to reproduce:**
N/A

**Related Issues:**
Redmine - https://redmine.wso2.com/issues/169

**Comment by Nirthika** [comment]
This issue is resolved by release sample CMIS Connector in Git [1] and store [2]
[1] https://github.com/wso2-extensions/esb-connector-cmis
[2] https://store.wso2.com/store/assets/esbconnector/details/53877590-3360-40b5-81c2-a75e9f559d50
